basePath: /
definitions:
  types.PostTaskHandlerRequest:
    properties:
      task_code:
        type: string
      task_translator:
        type: string
    type: object
  types.PostUserLoginHandlerRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  types.PostUserRegisterHandlerRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a code runner.
  title: http_server
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Logins new user and creates new session for him
      parameters:
      - description: user login and password
        in: body
        name: name
        required: true
        schema:
          $ref: '#/definitions/types.PostUserLoginHandlerRequest'
      responses:
        "200":
          description: OK
          schema:
            type: user
        "400":
          description: Bad request
          schema:
            type: string
        "404":
          description: Not found
          schema:
            type: string
      summary: Login a user
      tags:
      - user
  /register:
    post:
      consumes:
      - application/json
      description: Registers new user and adds them to data base
      parameters:
      - description: user login and password
        in: body
        name: name
        required: true
        schema:
          $ref: '#/definitions/types.PostUserRegisterHandlerRequest'
      responses:
        "201":
          description: Created
        "208":
          description: Key already exists
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
      summary: Register a user
      tags:
      - user
  /task:
    post:
      consumes:
      - application/json
      description: Create a new task with the specified key and value
      parameters:
      - description: task code and translator
        in: body
        name: translation_data
        required: true
        schema:
          $ref: '#/definitions/types.PostTaskHandlerRequest'
      - description: Bearer token for authentication
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: task
        "400":
          description: Bad request
          schema:
            type: string
      summary: Create an task
      tags:
      - task
  /task/result/{id}:
    get:
      consumes:
      - application/json
      description: Get a task result by its id
      parameters:
      - description: Id of the task
        in: path
        name: id
        required: true
        type: string
      - description: Bearer token for authentication
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: task
        "400":
          description: Bad request
          schema:
            type: string
        "404":
          description: Task not found
          schema:
            type: string
      summary: Get a task result
      tags:
      - task
  /task/status/{id}:
    get:
      consumes:
      - application/json
      description: Get a task status by its id
      parameters:
      - description: Id of the task
        in: path
        name: id
        required: true
        type: string
      - description: Bearer token for authentication
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: task
        "400":
          description: Bad request
          schema:
            type: string
        "404":
          description: Task not found
          schema:
            type: string
      summary: Get a task status
      tags:
      - task
swagger: "2.0"
